networks:
  app-tier:
    driver: bridge

version: '3'
services:
  database:
    image: mysql:8.0.31
    networks:
      - app-tier
    container_name: learningcampus
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=learningcampus
    ports:
      - 3306:3306
  backend:
    networks:
      - app-tier
    build: './backend'
    ports:
      - '8080:8080'
    depends_on:
      - database

  fronend:
    networks:
      - app-tier
    build: './frontend'
    ports:
      - '80:3000'
    depends_on:
      - backend
